name: Publish Namadillo to Laconic Registry
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - deploy-webapp

env:
  CERC_REGISTRY_USER_KEY: ${{ secrets.CICD_LACONIC_USER_KEY }}
  CERC_REGISTRY_BOND_ID: ${{ secrets.CICD_LACONIC_BOND_ID }}
  CERC_REGISTRY_RPC_ENDPOINT: "https://laconicd-sapo.laconic.com"
  CERC_REGISTRY_GQL_ENDPOINT: "https://laconicd-sapo.laconic.com/api"
  CERC_REGISTRY_CHAIN_ID: "laconic-testnet-2"
  CERC_REGISTRY_DEPLOYMENT_HOSTNAME: namadillo
  DEPLOYER_LRN: "lrn://vaasl-provider/deployers/webapp-deployer-api.apps.vaasl.io"

jobs:
  cns_publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Enable Yarn"
        run: corepack enable
      - name: "Install registry CLI"
        run: |
          npm config set @cerc-io:registry https://git.vdb.to/api/packages/cerc-io/npm/
          npm install -g @cerc-io/laconic-registry-cli          
      - name: "Install jq"
        run: sudo apt -y update && sudo apt -y install jq
      - name: "Publish Application Record"
        run: scripts/publish-app-record.sh
      - name: "Request Deployment"
        run: scripts/request-app-deployment.sh

